name: pure_clean_architecture_cli
description: A dart cli for generating Clean Architecture inside lib folder under features directory.
version: 1.2.2
repository: https://github.com/AgnelSelvan/pure_clean_architecture_cli.git

environment:
  sdk: '>=2.18.6 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
